kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: prod
  name: code-server-pvc-nfs
spec:
  storageClassName: nfs-client
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
